### ISSUE TITLE
500 error when authorising

### ISSUE THREAD

**Issue by sarahk** [XeroAPI/xero-php-oauth2-app#10]
I'm just getting started, have checked that authorization.php & callback.php have the right values that get passed into Provider.

I get a 500 error 

https://login.xero.com/identity/error?errorId=CfDJ8PDGFG5a0a...

With no additional info to help with debugging. 

Inspect's Network tab shows:
authorization.php
authorize?scope=openid%20email%20profile...
error?errorId=CfDJ8PDGFG5a0a...

**Comment by MattR-Api** [comment]
Hi @sarahk 

Thanks for getting in touch, it sounds like there may be an issue with the Authorisation URL you're generating. As this isn't a PHP specific issue, I'll shut the thread down. 

In terms of troubleshooting this however, please make sure that the Client ID has been entered correctly, you have no misspelt scopes and that the Redirect URI matches exactly what you have on your My Apps page of the Developer Centre. If you continue to have issues, please get in touch with us at api@xero.com with the Full Authorisation URL you're using and we'll be happy to help. 

Kind Regards

Matt
