### ISSUE TITLE
Offset error on redirect. Issue in JWTClaims.php

### ISSUE THREAD

**Issue by matthewyeow** [XeroAPI/xero-php-oauth2-app#12]
PHP example does not complete when you redirect. You receive an offset error.

It occurs on line 42 in callback.php. It is regarding the JWTClaims. This block of code seems to just echo out a name and is not necessary for the example to complete. Suggest removing it, or adding checks to prevent error.

**Comment by berenddeboer** [comment]
Thanks so much, got this weird error. Other things you see "malformed json" (added for those who are searching the tickets).

**Comment by SidneyAllen** [comment]
Thanks @matthewyeow - i've updated to version 1.2.0 of the SDK and fixed the callback.php to properly set the tokenId on the JWT class so it can be decoded.
