### ISSUE TITLE
Supplied parameter 'Ids' cannot be parsed.

### ISSUE THREAD

**Issue by maryglo** [XeroAPI/xero-php-oauth2-app#17]
tried to call the function getContacts() with required parameters and added parameter for $i_ids. According to the function description      
* @param  string[] $i_ds Filter by a comma separated list of ContactIDs. Allows you to retrieve a specific set of contacts in a single call. (optional)
Also checked the coded and there's handling i f you pass a string only or an array of contact ids. 
But when I tried it, I encountered an error
atal error: Uncaught XeroAPI\XeroPHP\ApiException: [400] Client error: `GET https://api.xero.com/api.xro/2.0/Contacts?IDs=7ea42cf-d555-4ec8-831d-87599d461b60` resulted in a `400 Bad Request` response: Supplied parameter 'Ids' cannot be parsed. 

Also, may I know if there is function that I can use to get  a contact by contact Id?

Bet Regards,
Mary

**Comment by SidneyAllen** [comment]
@maryglo 

Try using getContact and pass in a contactId

$result = $apiInstance->getContacts($xeroTenantId, $contactId);

**Comment by dr-ummond** [comment]
@SidneyAllen 

Any progress on this when I attempt to pass in string of comma separated id's I get

resulted in a `400 Bad Request` response:
Supplied parameter 'Ids' cannot be parsed.

**Comment by SidneyAllen** [comment]
@dr-ummond - we have runnable code snippets in our SDK reference docs now.

https://xeroapi.github.io/xero-php-oauth2/docs/v2/accounting/index.html#api-Accounting-getContacts

Here is an even simplier example 

    $iDs = array("1270bf7c-5d18-473a-9231-1e36c4bd33ed","2a251e97-9988-4e48-a76d-458cb5aae69a");
      
    try {
        $result = $apiInstance->getContacts($xeroTenantId, null, null, null, $iDs);
    } catch (Exception $e) {
        echo 'Exception when calling AccountingApi->getContacts: ', $e->getMessage(), PHP_EOL;
    }
