### ISSUE TITLE
TaxRates

### ISSUE THREAD

**Issue by gkavaliu** [XeroAPI/xero-php-oauth2-app#2]
Hello,

I am having trouble with reading the taxRates.

$result = $apiInstance->getTaxRates($xeroTenantId); 						

Result
Exception when calling AccountingApi: Invalid value for 'report_tax_type', must be one of 'OUTPUT', 'INPUT', 'EXEMPTOUTPUT', 'INPUTTAXED', 'BASEXCLUDED', 'EXEMPTEXPENSES', 'EXEMPTINPUT', 'ECOUTPUT', 'ECOUTPUTSERVICES', 'ECINPUT', 'ECACQUISITIONS', 'CAPITALSALESOUTPUT', 'CAPITALEXPENSESINPUT', 'MOSSSALES', 'NONE', 'GSTONIMPORTS', 'AVALARA'

**Comment by gkavaliu** [comment]
I solved the error by adding the missing types in:
xeroapi/xero-php-oauth2/lib/Models/Accounting/TaxRate.php

const REPORT_TAX_TYPE_NONEOUTPUT = 'NONEOUTPUT';
const REPORT_TAX_TYPE_PURCHASESINPUT = 'PURCHASESINPUT';
const REPORT_TAX_TYPE_SALESOUTPUT = 'SALESOUTPUT';

Not sure how to make changes for everyone

**Comment by SidneyAllen** [comment]
Thanks @gkavaliu I've updated the OAS and regenerated the PHP SDK to version 0.2.7

This sample app uses that now.  Thanks
