### ISSUE TITLE
Problem with the certificate being rejected

### ISSUE THREAD

**Issue by Budrose** [XeroAPI/xero-php-oauth2-app#24]
Below error message. Works fine on my local machine but an issue when I run it on my client's server

Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\xampp\htdocs\xero-printcOauth2\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:201 Stack trace: #0 C:\xampp\htdocs\xero-printcOauth2\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\xampp\htdocs\xero-printcOauth2\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 C:\xampp\htdocs\xero-printcOauth2\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) in C:\xampp\htdocs\xero-printcOauth2\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 201

**Comment by SidneyAllen** [comment]
@Budrose - This sounds like an issue with your hosting environment/certificates and guzzle.  

While the xero-php-oauth2 SDK uses guzzle, we aren't the best ppl to trouble shoot this.  A quick google turned up several issues on the guzzle repository.  Sounds like there are various ways you could try to solve this for your unique situation.

https://github.com/guzzle/guzzle/issues/1935
https://github.com/guzzle/guzzle/issues/394
