### ISSUE TITLE
Using getDate() on Invoice.php how do i format it to dd-mm-yyyy

### ISSUE THREAD

**Issue by Budrose** [XeroAPI/xero-php-oauth2-app#27]
Please help if you can. Thank you

**Comment by SidneyAllen** [comment]
@Budrose - Please see the README for changes in how to retrieve dates from models.  Let me know if that helps.

https://github.com/XeroAPI/xero-php-oauth2#changes-in-version-2x

**Comment by Budrose** [comment]
Thank you



Brenda Walker
IT Consultant
netwebsolutionsnz@gmail.com
021 910 975
