### ISSUE TITLE
cURL error 60

### ISSUE THREAD

**Issue by Cloudinnovates** [XeroAPI/xero-php-oauth2-app#3]
Getting following error 

cURL error 60: SSL certificate problem: unable to get local issuer certificate

Please advise urgently
Thanks

**Comment by MattR-Api** [comment]
Hi @Cloudinnovates 

Thanks for raising this with us, however it doesn't appear to be an issue related directly with the SDK so I'm going to close this thread. 

I had a quick search on the web for your error however, and I found the following which may relate to your issue: https://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate

Hope that helps.

Cheers

Matt

**Comment by Cloudinnovates** [comment]
Thanks, Matt. It works.
