### ISSUE TITLE
Get Contacts always returns null

### ISSUE THREAD

**Issue by anchordigi** [XeroAPI/xero-php-oauth2-app#32]
I'm trying to get contacts via email address, but whatever I do returns no results. I've tried using the ID parameter too but still returned nothing.

 Here's what i'm doing:
 
`
$apiInstance = $this->config();
$storage = new StorageClass();
$xeroTenantId = (string)$storage->getSession()['tenant_id'];

$ifModifiedSince = new DateTime("2019-02-06T12:17:43.202-08:00");
        $where = 'EmailAddress="email@me.com"';
        $order = "Name ASC";
        $iDs = array();
        $page = 1;
        $includeArchived = true;

        try {
          $result = $apiInstance->getContacts($xeroTenantId, $ifModifiedSince, $where, $order, $iDs, $page, $includeArchived);
        } catch (Exception $e) {
          var_dump($e->getMessage());
           echo 'Exception when calling AccountingApi->getContacts: ', $e->getMessage(), PHP_EOL;
        }`

I set up the AccountingApi in my config function, so that's not included in that cope snippet. That part is working though, I just can't figure out how to get the query working.

I'm using a Xero demo company and there is a contact with the email 'email@me.com'.

Thanks for any help!

**Comment by SidneyAllen** [comment]
@anchordigi thanks for your question.

Looking at your code - the "where" clause doesn't look right.

I think this might do the trick.
$where = 'EmailAddress=="email@me.com"';

Also, we have runnable code examples in our new documentation for the SDK
https://xeroapi.github.io/xero-php-oauth2/docs/v2/accounting/index.html#api-Accounting-getContacts

Let us know if this helps
