### ISSUE TITLE
Fatal error: Uncaught Error

### ISSUE THREAD

**Issue by rockers007** [XeroAPI/xero-php-oauth2-app#35]
Fatal error: Uncaught Error: Call to undefined function GuzzleHttp\Psr7\build_query()
getting this error on callback.php

**Comment by pumpkinball** [comment]
Hi @rockers007 thanks for picking this up. There is a pull request in the main library here https://github.com/XeroAPI/xero-php-oauth2/pull/249

**Comment by RettBehrens** [comment]
Resolved in the latest [release](https://github.com/XeroAPI/xero-php-oauth2/releases/tag/2.11.0). Made the necessary changes upstream in our code generator repo.
