### ISSUE TITLE
Trying sample software with MAMP install

### ISSUE THREAD

**Issue by ClevelyDynamic** [XeroAPI/xero-php-oauth2-app#36]
Just installed MAMP and composer, cloned this repo, allows the connection and on callback seems to be failing with this... using lastetst MAMP, so php 8.01 - used MAMP so i could test without using SSL etc. just want to see if it works...

I have double checked the Xero setup side, callback in the .env file is set to...
http://localhost/xero-php-oauth2-app/callback.php

Not sure what else to check / what else I have  / have not done...

Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://identity.xero.com/connect/token in E:\MAMP\htdocs\xero-php-oauth2-app\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:211 Stack trace: #0 E:\MAMP\htdocs\xero-php-oauth2-app\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 E:\MAMP\htdocs\xero-php-oauth2-app\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 E:\MAMP\htdocs\xero-php-oauth2-app\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 E:\MAMP\htdocs\xero-php-oauth2-app\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array) #4 E:\MAMP\htdocs\xero-php-oauth2-app\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array) #5 E:\MAMP\htdocs\xero-php-oauth2-app\vendor\guzzlehttp\guzzle\src\PrepareBodyMiddleware.php(64): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array) #6 E:\MAMP\htdocs\xero-php-oauth2-app\vendor\guzzlehttp\guzzle\src\Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array) #7 E:\MAMP\htdocs\xero-php-oauth2-app\vendor\guzzlehttp\guzzle\src\RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array) #8 E:\MAMP\htdocs\xero-php-oauth2-app\vendor\guzzlehttp\guzzle\src\Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array) #9 E:\MAMP\htdocs\xero-php-oauth2-app\vendor\guzzlehttp\guzzle\src\HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array) #10 E:\MAMP\htdocs\xero-php-oauth2-app\vendor\guzzlehttp\guzzle\src\Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array) #11 E:\MAMP\htdocs\xero-php-oauth2-app\vendor\guzzlehttp\guzzle\src\Client.php(107): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array) #12 E:\MAMP\htdocs\xero-php-oauth2-app\vendor\guzzlehttp\guzzle\src\Client.php(123): GuzzleHttp\Client->sendAsync(Object(GuzzleHttp\Psr7\Request), Array) #13 E:\MAMP\htdocs\xero-php-oauth2-app\vendor\league\oauth2-client\src\Provider\AbstractProvider.php(608): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request)) #14 E:\MAMP\htdocs\xero-php-oauth2-app\vendor\league\oauth2-client\src\Provider\AbstractProvider.php(621): League\OAuth2\Client\Provider\AbstractProvider->getResponse(Object(GuzzleHttp\Psr7\Request)) #15 E:\MAMP\htdocs\xero-php-oauth2-app\vendor\league\oauth2-client\src\Provider\AbstractProvider.php(537): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request)) #16 E:\MAMP\htdocs\xero-php-oauth2-app\callback.php(39): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken(Object(League\OAuth2\Client\Grant\AuthorizationCode), Array) #17 {main} thrown in E:\MAMP\htdocs\xero-php-oauth2-app\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 211

**Comment by ClevelyDynamic** [comment]
Thought I would leave a comment here just in case someone else has the problem... there are in fact several problems with the Guzzle http part.

1) You need to download the .pem file from here https://curl.se/docs/caextract.html then point to it in your php.ini file I put in curl.cainfo="E:/cacert.pem" I dumped it somewhere for a quick test.

2) Then guzzle will complain about using GuzzleHttp\Psr7\build_query() you need to replace all instances of build_query with Query::build

**Comment by RettBehrens** [comment]
We're currently running PHP version `7.x` and it's on our priority list to look to support version `8.x`.

The `build_query` error was resolved in the latest [release](https://github.com/XeroAPI/xero-php-oauth2/releases/tag/2.11.0). Made the necessary changes upstream in our code generator repo.
