### ISSUE TITLE
Xero integration

### ISSUE THREAD

**Issue by arifuss** [XeroAPI/xero-php-oauth2-app#40]
Hi,
We have a CRM software at our organization and we intend to connect it with Xero where our invoices and payments are connected and data is transferred from Software to Xero. We seek your guidance on API and coding to get it done. We are using PHP version 5.6.40.

**Comment by AuCourant-Cyberspace-Private-Limited** [comment]
> Hi, We have a CRM software at our organisation and we intend to connect it with Xero where our invoices and payments are connected and data is transferred from Software to Xero. We seek your guidance on API and coding to get it done. We are using PHP version 5.6.40.

Hello Arifuss, I am a developer based in India and have recently implemented this API integration for a UK based client integrating Xero with their Wordpress website and third party Software.  Kindly drop me a mail on hello@aucourantcyberspace.com in case you are interested.

Thanks
