### ISSUE TITLE
connect to xero for error 500

### ISSUE THREAD

**Issue by fredmanxu** [XeroAPI/xero-php-oauth2-app#5]
### I'm runned xero-php-oauth2-app and click connect to xero button

![image](https://user-images.githubusercontent.com/20528643/70017624-8e160a00-15be-11ea-8fa5-c660822ae2c5.png)
![image](https://user-images.githubusercontent.com/20528643/70017652-9d955300-15be-11ea-9279-4ac12032dedc.png)

**Comment by SidneyAllen** [comment]
Hi @landyXU 

Did you create your Xero app and set your Client Id and Secret?

https://github.com/XeroAPI/xero-php-oauth2-app#add-your-api-keys-to-this-app

**Comment by fredmanxu** [comment]
Yes, I'm created Xero App and set my Client Id and Secret.

**Comment by SidneyAllen** [comment]
@landyXU can you confirm that the RedirectURI you set for your Xero app at https://developer.xero.com/myapps  matches the RedirectURI that is set in the code.

$provider = new \League\OAuth2\Client\Provider\GenericProvider([
        'clientId'                => '__YOUR_CLIENT_ID__',   
        'clientSecret'            => '__YOUR_CLIENT_SECRET__',
        **'redirectUri'             => 'http://localhost:8888/xero-php-oauth2-app/callback.php',**
	    'urlAuthorize'            => 'https://login.xero.com/identity/connect/authorize',
	    'urlAccessToken'          => 'https://identity.xero.com/connect/token',
	    'urlResourceOwnerDetails' => 'https://api.xero.com/api.xro/2.0/Organisation'
	]);

**Comment by gofodtech** [comment]
Hi @SidneyAllen,

I'm also having this issue too...

https://crm.gofodtech.co.uk/xero-php-oauth2-app/

I have confirmed that the clientId, clientSecret, and redirectUri are all set correctly in authorization.php, callback.php, get.php, and the .env file.

Any ideas please?
