### ISSUE TITLE
500 Error when trying to connect

### ISSUE THREAD

**Issue by gofodtech** [XeroAPI/xero-php-oauth2-app#7]
Hi there!

I've just installed this great toolkit using Composer.  But I can't seem to get it to work!

I go to https://crm.gofodtech.co.uk/xero-php-oauth2-app/

![1](https://user-images.githubusercontent.com/59477807/71727138-42f74d00-2e31-11ea-9de8-a26f2766bebe.png)

I then get...

![2](https://user-images.githubusercontent.com/59477807/71727153-4e4a7880-2e31-11ea-8e10-b1fe37641a14.png)

I have confirmed that the clientId, clientSecret, and redirectUri are all set correctly in authorization.php, callback.php, get.php, and the .env file, in accordance with my app at developer.xero.com.

Any ideas please?

Thank you!

Gofod.

**Comment by gofodtech** [comment]
I've just figured it out!  Since xero-php-oauth2-app is now using .env, you don't need to change the authorization.php, callback.php, or get.php files.  You just put your clientId, clientSecret, and redirectUri inside the sample.env file and then rename it to .env.

It might be worth updating the installation instructions to reflect this as it may confuse others like it did me.

**Comment by SidneyAllen** [comment]
@gofodtech - thanks for the feedback - README has been updated
