### ISSUE TITLE
Quotations

### ISSUE THREAD

**Issue by gofodtech** [XeroAPI/xero-php-oauth2-app#9]
Hi there,

I'm trying to retrieve quotations from Xero by using the GetQuote function in the API but it is failing with...

Exception when calling AccountingApi: [401] Client error: `GET https://api.xero.com/api.xro/2.0/Quotes/92c497ca-dd61-4a8c-8a0f-fec8c8495ee2` resulted in a `401 Unauthorized` response: oauth_problem=consumer_key_unknown&oauth_problem_advice=Consumer%20key%20was%20not%20recognised

Any ideas please?  Everything else is working great!

Thanks,

Darren.

**Comment by MattR-Api** [comment]
Hi @gofodtech 

As this isn't a PHP specific issue, we'll shut this thread down. 

If you're receving a 401 Unauthorised error, it may be that the Scope for the endpoint you're calling hasn't been included during Authorisation. For Quotes the correct Scope is accounting.transactions.

If you're still facing this problem, could you please get in touch with us at api@xero.com so we can help you get to the bottom of this? 

Kind Regards

Matt
